"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
export default function Dashboard(){
 const[t,setT]=useState(""); const[msg,setMsg]=useState(""); const[busy,setBusy]=useState(false);
 const[apps,setApps]=useState<any[]>([]),[agents,setAgents]=useState<any[]>([]),[spaces,setSpaces]=useState<any[]>([]),[mem,setMem]=useState<any[]>([]),[results,setResults]=useState<any[]>([]);
 const[appName,setAppName]=useState(""),[agentName,setAgentName]=useState(""),[appId,setAppId]=useState(""),[agentId,setAgentId]=useState("");
 const[nsName,setNsName]=useState("default"),[nsId,setNsId]=useState(""),[retention,setRetention]=useState("30");
 const[content,setContent]=useState(""),[tags,setTags]=useState(""),[meta,setMeta]=useState('{}'),[importance,setImportance]=useState(.7),[expires,setExpires]=useState("");
 const[q,setQ]=useState(""),[mode,setMode]=useState("hybrid"),[start,setStart]=useState(""),[end,setEnd]=useState("");
 const[keys,setKeys]=useState<any[]>([]),[newKey,setNewKey]=useState(""),[analytics,setAnalytics]=useState<any>(null),[usage,setUsage]=useState<any[]>([]);
 const[rate,setRate]=useState<any>(null),[shared,setShared]=useState<any[]>([]),[ready,setReady]=useState<any>(null);
 const[shareEmail,setShareEmail]=useState(""),[role,setRole]=useState("viewer"),[privacy,setPrivacy]=useState(true);
 useEffect(()=>{const x=localStorage.getItem("cv_token")||"";setT(x);if(x)refresh(x)},[]);
 async function call(path:string,opts:any={},token=t){const r=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json",Authorization:"Bearer "+token,...opts.headers}});let d:any={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||`Request failed (${r.status})`);return d}
 async function act(fn:()=>Promise<any>){setBusy(true);setMsg("");try{return await fn()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function refresh(x=t){await act(async()=>{const [a,g,n,m,k,an,u,rl,sh,me,rd]=await Promise.all([call("/api/v1/applications",{},x),call("/api/v1/agents",{},x),call("/api/v1/namespaces",{},x),call("/api/v1/memories",{},x),call("/api/v1/api-keys",{},x),call("/api/v1/analytics",{},x),call("/api/v1/api-usage",{},x),call("/api/v1/rate-limit",{},x),Promise.resolve([]),call("/api/v1/auth/me",{},x),call("/api/v1/system/readiness",{},x)]);setApps(a);setAgents(g);setSpaces(n);setMem(m);setKeys(k);setAnalytics(an);setUsage(u);setRate(rl);setShared(sh);setPrivacy(me.privacy_mode);setReady(rd)})}
 async function createApp(){await act(async()=>{const d=await call("/api/v1/applications",{method:"POST",body:JSON.stringify({name:appName})});setAppId(d.id);setMsg("Application created");refresh()})}
 async function createAgent(){await act(async()=>{const d=await call("/api/v1/agents",{method:"POST",body:JSON.stringify({application_id:appId,name:agentName,namespace:"default"})});setAgentId(d.id);setMsg("Agent created");refresh()})}
 async function createNs(){await act(async()=>{const d=await call("/api/v1/namespaces",{method:"POST",body:JSON.stringify({agent_id:agentId,name:nsName,retention_days:Number(retention)||null})});setNsId(d.id);setMsg("Namespace created");refresh()})}
 async function save(){await act(async()=>{let metadata={};try{metadata=JSON.parse(meta)}catch{throw new Error("Metadata must be valid JSON")};const d=await call("/api/v1/memories",{method:"POST",body:JSON.stringify({agent_id:agentId,namespace_id:nsId||null,content,tags:tags.split(",").map(x=>x.trim()).filter(Boolean),metadata,importance,expires_at:expires?new Date(expires).toISOString():null})});setMsg(d.duplicate?"Duplicate detected — existing memory returned":"Memory saved");setContent("");refresh()})}
 async function search(){await act(async()=>setResults(await call("/api/v1/memories/search",{method:"POST",body:JSON.stringify({query:q,mode,agent_id:agentId||null,namespace_id:nsId||null,start_date:start?new Date(start).toISOString():null,end_date:end?new Date(end).toISOString():null})})))}
 async function mutate(id:string,action:string,method="POST"){await act(async()=>{await call(`/api/v1/memories/${id}${action}`,{method});setMsg("Memory updated");refresh()})}
 async function editMemory(x:any){const next=prompt("Edit memory",x.content);if(next===null||next.trim()==="")return;await act(async()=>{await call(`/api/v1/memories/${x.id}`,{method:"PUT",body:JSON.stringify({content:next})});setMsg("Memory edited");refresh()})}
 async function similar(id:string){await act(async()=>{setResults(await call(`/api/v1/memories/${id}/similar`));setMsg("Similar memories")})}
 async function createKey(){await act(async()=>{const d=await call("/api/v1/api-keys",{method:"POST",body:JSON.stringify({name:"dashboard-key"})});setNewKey(d.api_key);refresh()})}
 async function revoke(id:string){await act(async()=>{await call(`/api/v1/api-keys/${id}/revoke`,{method:"POST"});refresh()})}
 async function share(){await act(async()=>{await call(`/api/v1/permissions?application_id=${appId}&user_email=${encodeURIComponent(shareEmail)}&role=${role}`,{method:"POST"});setMsg("Permission added")})}
 async function enforce(){await act(async()=>{const d=await call("/api/v1/retention/enforce",{method:"POST"});setMsg(`Retention enforced: ${d.archived} archived`);refresh()})}
 async function testRetrieval(){await act(async()=>{const d=await call("/api/v1/retrieval-test",{method:"POST",body:JSON.stringify({query:q,mode,limit:10})});setResults(d.results);setMsg(`Retrieval test returned ${d.count}`)})}
 async function evaluate(){await act(async()=>{const d=await call("/api/v1/evaluation",{method:"POST",body:JSON.stringify({query:q,mode,limit:10})});setMsg(`Search evaluation — returned ${d.returned}; ${d.precision_at_k!=null?`precision ${d.precision_at_k}, recall ${d.recall_at_k}`:`proxy precision ${d.lexical_precision_proxy}`}`)})}
 async function togglePrivacy(){await act(async()=>{const d=await call(`/api/v1/privacy?enabled=${!privacy}`,{method:"POST"});setPrivacy(d.privacy_mode);setMsg("Privacy setting updated")})}
 async function exportData(){await act(async()=>{const d=await call("/api/v1/export");const blob=new Blob([JSON.stringify(d,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="contextvault-memories.json";a.click();URL.revokeObjectURL(a.href)})}
 if(!t)return <main className="shell"><div className="card"><h2>Authentication required</h2><a className="button" href="/login">Login</a></div></main>;
 return <main className="shell">
 <nav className="nav"><div className="brand"><img src="/contextvault-logo.svg" width="40" height="40" alt="ContextVault logo"/> ContextVault</div><button className="button" onClick={()=>{localStorage.removeItem("cv_token");location.href="/login"}}>Logout</button></nav>
 <h1>Memory Infrastructure Dashboard</h1>{shared.length>0&&<p className="muted">Shared applications: {shared.map(x=>`${x.name} (${x.role})`).join(", ")}</p>}<p className="muted">Applications, agents, namespaces, retrieval, API access, privacy and analytics.</p>
 
 {msg&&<div className="notice">{msg}</div>}{busy&&<div className="muted">Working…</div>}
 <section className="stats"><div className="card"><b>{analytics?.memory_count??0}</b><span>Memories</span></div></section>
 <section className="grid"><div className="card"><h3>Application</h3><input className="input" value={appName} onChange={e=>setAppName(e.target.value)} placeholder="Application name"/><button className="button" onClick={createApp}>Create application</button><select className="input" value={appId} onChange={e=>setAppId(e.target.value)}><option value="">Select application</option>{apps.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
 <div className="card"><h3>Agent</h3><input className="input" value={agentName} onChange={e=>setAgentName(e.target.value)} placeholder="Agent name"/><button className="button" onClick={createAgent} disabled={!appId}>Create agent</button><select className="input" value={agentId} onChange={e=>setAgentId(e.target.value)}><option value="">Select agent</option>{agents.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
 <div className="card"><h3>Namespace & retention</h3><input className="input" value={nsName} onChange={e=>setNsName(e.target.value)} placeholder="Namespace"/><input className="input" type="number" value={retention} onChange={e=>setRetention(e.target.value)} placeholder="Retention days"/><button className="button" onClick={createNs} disabled={!agentId}>Create namespace</button><select className="input" value={nsId} onChange={e=>setNsId(e.target.value)}><option value="">No namespace</option>{spaces.filter(x=>!agentId||x.agent_id===agentId).map(x=><option key={x.id} value={x.id}>{x.name} ({x.retention_days||"âˆž"} days)</option>)}</select><button className="button secondary" onClick={enforce}>Enforce retention</button></div></section>
 <section className="card"><h2>Create memory</h2><textarea className="textarea" value={content} onChange={e=>setContent(e.target.value)} placeholder="Memory content"/><div className="grid"><input className="input" value={tags} onChange={e=>setTags(e.target.value)} placeholder="Tags: customer, preference"/><input className="input" type="number" min="0" max="1" step=".1" value={importance} onChange={e=>setImportance(Number(e.target.value))}/><input className="input" type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></div><button className="button" onClick={save} disabled={!agentId||!content}>Save memory</button></section>
 <section className="card"><h2>Search & retrieval</h2><div className="grid"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search query"/><select className="input" value={mode} onChange={e=>setMode(e.target.value)}><option value="hybrid">Hybrid</option><option value="semantic">Semantic</option><option value="keyword">Keyword</option></select><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div><div className="actions"><button className="button" onClick={search}>Search</button><button className="button secondary" onClick={testRetrieval}>Retrieval test</button><button className="button secondary" onClick={evaluate}>Evaluate quality</button></div>{results.map(x=><div className="memory" key={x.id}><b>{x.content}</b><span className="muted">{x.score!=null?` score ${x.score}`:x.similarity!=null?` similarity ${x.similarity}`:""}</span></div>)}</section>
 <section className="card"><h2>Memory library</h2>{mem.length===0?<p className="muted">No memories yet.</p>:mem.map(x=><div className="memory" key={x.id}><div><b>{x.content}</b><div className="muted">importance {x.importance} · {x.archived?"archived":"active"} · {(x.tags||[]).join(", ")}</div></div><div className="actions"><button onClick={()=>editMemory(x)}>Edit</button><button onClick={()=>similar(x.id)}>Similar</button>{x.archived?<button onClick={()=>mutate(x.id,"/restore")}>Restore</button>:<button onClick={()=>mutate(x.id,"/archive")}>Archive</button>}<button className="dangerBtn" onClick={()=>mutate(x.id,"","DELETE")}>Delete</button></div></div>)}</section>
 <section className="grid"><div className="card"><h2>API keys</h2><button className="button" onClick={createKey}>Generate API key</button>{newKey&&<div className="secret"><b>Copy now:</b><br/>{newKey}</div>}{keys.map(k=><div className="memory" key={k.id}><span>{k.name} · {k.revoked?"revoked":"active"}</span>{!k.revoked&&<button onClick={()=>revoke(k.id)}>Revoke</button>}</div>)}</div>
 <div className="card"><h2>Privacy & permissions</h2><p>Privacy mode: <b>{privacy?"On":"Off"}</b></p><button className="button secondary" onClick={togglePrivacy}>Toggle privacy</button><input className="input" value={shareEmail} onChange={e=>setShareEmail(e.target.value)} placeholder="User email"/><select className="input" value={role} onChange={e=>setRole(e.target.value)}><option>viewer</option><option>editor</option></select><button className="button" onClick={share} disabled={!appId||!shareEmail}>Add permission</button></div>
 <div className="card"><h2>Data & analytics</h2><button className="button" onClick={exportData}>Export memories JSON</button></div></section>
 <div className="footer">Powered by Codyza</div></main>
}




